### ISSUE TITLE
Expo app: Envelope header states wrong item size

### ISSUE THREAD

**Issue by petrleocompel** [getsentry/sentry-android#273]
_Platform:_
- [x]  Android
    - device SDK = 2
    - minSdkVersion = 21
    - targetSdkVersion = 28
    - compileSdkVersion = 28
    - buildToolsVersion = 28.0.0
    - supportLibVersion = 28.0.0
- [x]  Java -> JavaVersion.VERSION_1_8 / JavaVersion.VERSION_1_8
- [x]  Kotlin -> 1.3.21
- [ ]  NDK -> no

_IDE:_
- [ ]  Android Studio
- [x]  IntelliJ -> IntelliJ IDEA 2019.3.3 (Ultimate Edition) Build #IU-193.6494.35, built on February 11, 2020
- [ ]  Other

_Build system:_
- [x]  Gradle -> 4.10.1
- [ ]  Buck
- [ ]  Bazel
- [ ]  Other

_Android Gradle Plugin:_
- [x]  Yes -> 3.3.2
- [ ]  No

_Sentry Android Gradle Plugin:_
- [ ]  Yes
- [x]  No

_Proguard/R8:_
- [x]  Enabled
- [ ]  Disabled

_sentry-android installed with:_
- [ ] JCenter
- [x] Bintray
- [ ] Manually

The version of sentry-android:
**2.0.0-rc4**

---
I have the following issue:

After crash with React native or in Java sentry is trying to send event but
```
E/FileObserver: Unhandled exception in FileObserver io.sentry.android.core.EnvelopeFileObserver@c1c6254
    java.lang.IllegalArgumentException: Invalid envelope. Item at index '1'. has no header delimiter.
        at io.sentry.core.EnvelopeReader.read(EnvelopeReader.java:83)
        at io.sentry.core.EnvelopeSender.processFile(EnvelopeSender.java:50)
        at io.sentry.core.EnvelopeSender.processEnvelopeFile(EnvelopeSender.java:79)
        at io.sentry.android.core.EnvelopeFileObserver.onEvent(EnvelopeFileObserver.java:42)
        at android.os.FileObserver$ObserverThread.onEvent(FileObserver.java:163)
        at android.os.FileObserver$ObserverThread.observe(Native Method)
        at android.os.FileObserver$ObserverThread.run(FileObserver.java:113)
```

I recieved content of file there which is
```
{"event_id":"695b947ce1f84d59b471a5663928d697"}
{"content_type":"application/json","length":7438,"type":"event"}
{"exception":{"values":[{"type":"Error","value":"Non-Error exception captured with keys: _bodyBlob, _bodyInit, headers, ok","mechanism":{"synthetic":true,"handled":true,"type":"generic"},"stacktrace":{}}]},"extra":{"manifest":{"id":"slug","name":"Dispečink","slug":"slug","description":"Dispečink","entryPoint":"./index.js","locales":{},"orientation":"default","primaryColor":"#cccccc","privacy":"public","sdkVersion":"UNVERSIONED","minVersion":"1.2.0","bundleUrl":"http://10.0.0.119:5000/main.android.bundle","hostUri":"localhost/bundles/slug","releaseChannel":"default","version":"release-1","revisionId":"release-1","publishedTime":"2020-02-06T11:14:44.066Z","loadedFromCache":false,"isVerified":true},"deviceYearClass":2014,"linkingUri":"exp://10.0.0.119:5000","__serialized__":{"type":"default","status":500,"ok":false,"statusText":"[undefined]","headers":{"map":"[Object]"},"url":"http://localhost/api/aktualniposadka?_t=1582029980615","_bodyInit":{"_data":"[Object]"},"_bodyBlob":{"_data":"[Object]"}}},"level":"error","event_id":"695b947ce1f84d59b471a5663928d697","platform":"javascript","sdk":{"name":"sentry.javascript.react-native","packages":[{"name":"npm:@sentry/react-native","version":"1.3.1"}],"version":"1.3.1","integrations":["Release","InboundFilters","FunctionToString","LinkedErrors","UserAgent","Breadcrumbs","DeviceContext","ReactNativeErrorHandlers","ExpoIntegration","RewriteFrames"]},"release":"host.exp.exponent.sc@1.3.1-null+1","tags":{"deviceId":"cf076abf-4da9-497f-965c-9222ca1d0ff2","appOwnership":"expo","expoVersion":"1.3.1-null","expoReleaseChannel":"default","expoAppVersion":"release-1","expoAppPublishedTime":"2020-02-06T11:14:44.066Z"},"breadcrumbs":[{"timestamp":1582029979.275,"category":"console","data":{"arguments":["Running application \"main\" with appParams: {\"initialProps\":{\"exp\":{\"lastErrors\":[{\"isFatal\":true,\"errorMessage\":\"TEST - Sentry Client Crash (only works in release mode)\",\"exceptionId\":-1662664331}],\"initialUri\":\"exp://10.0.0.119:5000\",\"manifest\":{\"releaseChannel\":\"default\",\"iconUrl\":\"https://d3lwq5rlu14cro.cloudfront.net/ExponentEmptyManifest_192.png\",\"hostUri\":\"localhost/bundles/slug\",\"isVerified\":true,\"name\":\"Dispečink\",\"locales\":{},\"id\":\"slug\",\"version\":\"release-1\",\"sdkVersion\":\"UNVERSIONED\",\"minVersion\":\"1.2.0\",\"privacy\":\"public\",\"loadedFromCache\":false,\"orientation\":\"default\",\"bundleUrl\":\"http://10.0.0.119:5000/main.android.bundle\",\"primaryColor\":\"#cccccc\",\"revisionId\":\"release-1\",\"slug\":\"slug\",\"description\":\"Dispečink\",\"publishedTime\":\"2020-02-06T11:14:44.066Z\",\"entryPoint\":\"./index.js\"},\"shell\":false}},\"rootTag\":31}. __DEV__ === false, development-level warning are OFF, performance optimizations are ON"],"logger":"console"},"level":"log","message":"Running application \"main\" with appParams: {\"initialProps\":{\"exp\":{\"lastErrors\":[{\"isFatal\":true,\"errorMessage\":\"TEST - Sentry Client Crash (only works in release mode)\",\"exceptionId\":-1662664331}],\"initialUri\":\"exp://10.0.0.119:5000\",\"manifest\":{\"releaseChannel\":\"default\","isVerified\":true,\"name\":\"Dispečink\",\"locales\":{},\"id\":\"slug\",\"version\":\"release-1\",\"sdkVersion\":\"UNVERSIONED\",\"minVersion\":\"1.2.0\",\"privacy\":\"public\",\"loadedFromCache\":false,\"orientation\":\"default\",\"bundleUrl\":\"http://10.0.0.119:5000/main.android.bundle\",\"primaryColor\":\"#cccccc\",\"revisionId\":\"release-1\",\"slug\":\"slug\",\"description\":\"Dispečink\",\"publishedTime\":\"2020-02-06T11:14:44.066Z\",\"entryPoint\":\"./index.js\"},\"shell\":false}},\"rootTag\":31}. __DEV__ === false, development-level warning are OFF, performance optimizations are ON"},{"timestamp":1582029979.361,"category":"console","data":{"arguments":["Získáno",true],"logger":"console"},"level":"log","message":"Získáno true"},{"timestamp":1582029981.582,"category":"xhr","data":{"method":"GET","url":"http://localhost/api/vozidla?_t=1582029980624","status_code":200},"type":"http"},{"timestamp":1582029981.595,"category":"xhr","data":{"method":"GET","url":"http://localhost/api/technici?_t=1582029980631","status_code":200},"type":"http"},{"timestamp":1582029981.6,"category":"xhr","data":{"method":"GET","url":"http://localhost/api/aktualniposadkatabletu?_t=1582029980748","status_code":200},"type":"http"},{"timestamp":1582029981.608,"category":"xhr","data":{"method":"GET","url":"http://localhost/api/aktualniposadka?_t=1582029980615","status_code":500},"type":"http"},{"timestamp":1582029981.616,"category":"xhr","data":{"method":"POST","url":"http://localhost/api/registrujTablet","status_code":200},"type":"http"},{"timestamp":1582029981.665,"category":"xhr","data":{"method":"GET","url":"http://localhost/api/tiketstav/false?_t=1582029980445","status_code":500},"type":"http"},{"timestamp":1582029981.709,"category":"console","data":{"arguments":["[INFO] BackgroundGeolocation service is running",false],"logger":"console"},"level":"log","message":"[INFO] BackgroundGeolocation service is running false"},{"timestamp":1582029981.71,"category":"console","data":{"arguments":["[INFO] BackgroundGeolocation services enabled",true],"logger":"console"},"level":"log","message":"[INFO] BackgroundGeolocation services enabled true"},{"timestamp":1582029981.711,"category":"console","data":{"arguments":["[INFO] BackgroundGeolocation auth status: 1"],"logger":"console"},"level":"log","message":"[INFO] BackgroundGeolocation auth status: 1"},{"timestamp":1582029981.751,"category":"console","data":{"arguments":["BackgroundGeolocation config",{"postTemplate":"[Object]","maxLocations":10000,"httpHeaders":"[Object]","syncUrl":"","startOnBoot":false,"syncThreshold":100,"activitiesInterval":10000,"distanceFilter":50,"url":"http://localhost/api/udr/sledovani","fastestInterval":5000,"locationProvider":1,"notificationIconLarge":"","notificationsEnabled":true,"notificationIconSmall":"","stopOnStillActivity":true,"startForeground":true,"desiredAccuracy":0,"notificationTitle":"Dispečink - poloha","notificationText":"Sledování polohy aktivní","debug":false,"interval":10000,"notificationIconColor":"","stopOnTerminate":true,"stationaryRadius":50}],"logger":"console"},"level":"log","message":"BackgroundGeolocation config [object Object]"},{"timestamp":1582029982.19,"category":"xhr","data":{"method":"GET","url":"http://localhost/api/tiketstav/true?_t=1582029980744","status_code":500},"type":"http"}],"dist":"1","contexts":{"device":{"simulator":false,"model":"n/a"},"os":{"name":"Android","version":"29"}},"message":{}}
```

**Steps to reproduce:**
Not sure how to reproduce this. It's combination of Expo + Expo App + Android.

**Actual result:**
- Events failed to proccess

**Expected result:**
- Events to be uploaded to sentry server

**Comment by bruno-garcia** [comment]
Thanks a lot for the sample envelope, this is helpful! I'll take a look at this.

**Comment by marandaneto** [comment]
@petrleocompel hey, thanks for raising this issue, sending us the stack trace + envelope is just great :)
we'll be looking into it.

**Comment by tomershohet** [comment]
Hi,
I've had the exact same thing, no expo.

react-native: 0.59.9
The error keep on showing even on simple Sentry.captureMessage('title') event

2020-02-18 20:11:30.967 24199-24481/? E/FileObserver: Unhandled exception in FileObserver io.sentry.android.core.EnvelopeFileObserver@b131ff8
    java.lang.IllegalArgumentException: Invalid envelope. Item at index '1'. has no header delimiter.
        at io.sentry.core.EnvelopeReader.read(EnvelopeReader.java:83)
        at io.sentry.core.EnvelopeSender.processFile(EnvelopeSender.java:50)
        at io.sentry.core.EnvelopeSender.processEnvelopeFile(EnvelopeSender.java:79)
        at io.sentry.android.core.EnvelopeFileObserver.onEvent(EnvelopeFileObserver.java:42)
        at android.os.FileObserver$ObserverThread.onEvent(FileObserver.java:163)
        at android.os.FileObserver$ObserverThread.observe(Native Method)
        at android.os.FileObserver$ObserverThread.run(FileObserver.java:113)

**Comment by bruno-garcia** [comment]
Update: I've track down the issue to the "header of the envelope being of a different (bigger) size" than the actual item which indicates an issue on the part writing the envelope.
We'll investigate further to find out why this is happening and address it.

**Comment by marandaneto** [comment]
hey @petrleocompel https://github.com/getsentry/sentry-react-native/releases/tag/1.3.2 should fix this issue :) let us know if you find any issues, thanks

**Comment by petrleocompel** [comment]
I'm going to deeply test it these days.

Right now I'm dealing with error `k.extraUpdated(t._extra)` (sentry-react-native + sentry-expo). Not sure from where this is comming from but looks like `Envelope` error is fixed.

**Comment by bruno-garcia** [comment]
Thanks for reporting and testing.

**Comment by xwartz** [comment]
1.3.2 crash issue https://github.com/getsentry/sentry-react-native/issues/779
