### ISSUE TITLE
Permission problem with READ_PHONE_STATE on Android 4.4 and 5.0, due to using the android.telephony.TelephonyManager probably

### ISSUE THREAD

**Issue by bsergean** [getsentry/sentry-android#413]
_Platform:_
- [ ]  Android -> compileSdkVersion 28 / our min-version api is api 19.

_IDE:_
- [ ]  Other -> Command line build with gradle.

_Build system:_
- [ ]  Gradle -> If yes, which version?
- [ ]  Buck -> If yes, which version?
- [ ]  Bazel -> If yes, which version?
- [ ]  Other -> If yes, which one?

_Android Gradle Plugin:_
- [ ]  Yes -> If yes, which version?
- [ * ]  No

_Sentry Android Gradle Plugin:_
- [ ]  Yes -> If yes, which version?
- [ ]  No

_Proguard/R8:_
- [ ]  Enabled
- [ ]  Disabled

_sentry-android installed with:_
- [ * ] JCenter
- [ ] Bintray
- [ ] Maven Central
- [ ] Manually

The version of sentry-android:
**2.1.1**

---
I have the following issue:

```
E/AndroidRuntime( 1840): FATAL EXCEPTION: main
E/AndroidRuntime( 1840): Process: com.my.thing, PID: 1840
E/AndroidRuntime( 1840): java.lang.RuntimeException: Unable to get provider io.sentry.android.core.SentryInitProvider: java.lang.SecurityException: Neither user 10057 nor current process has android.permission.READ_PHONE_STATE.
```

**Steps to reproduce:**
- Step
```
        try
        {
            int divideByZero = 5 / 0; // should trigger an ArithmeticException 
        }
        catch (Exception e)
        {
            Sentry.captureException(e);
        }
```

**Comment by bsergean** [comment]
I can see this too on an Android 5.0 emulator (api 21) ?

**Comment by bsergean** [comment]
Maybe the emulator is messing up, but I wouldn't think so. This is on x86.

**Comment by bsergean** [comment]
FYI it works great on Android 7.0 API 24.

**Comment by bsergean** [comment]
Our local Android wizard says it might relate to the sdk querying the imei, but when I google for 'query imei programmatically' I find references to the telephony manager.

Not sure on the best way to fix this, my java-fu is very limited.

**Comment by bsergean** [comment]
Those things relate to the PhoneStateBreadcrumbsIntegration.java

Maybe that thing could be optional ? So that the default case works for old Android versions ?

**Comment by marandaneto** [comment]
hey @bsergean thanks for raising this.

this is already optional there's a flag `enableSystemEventBreadcrumbs`
I've tested with API 14 and it worked and permissions were only needed if we need the `incomingNumber` but we don't use it. I'll double-check this, thanks.

**Comment by marandaneto** [comment]
your PR does the right thing, I've made a new one though to move to the appropriate place.

This is indeed not written in the docs nor in the source code, it's not clear which versions require this extra permission or not, so I've gated the whole thing and added a generic`Exception` to avoid further problems.

Thanks @bsergean

**Comment by marandaneto** [comment]
https://github.com/getsentry/sentry-android/releases/tag/2.1.2

**Comment by bsergean** [comment]
You guys rock !!

I’ll give 2.1.2 a try asap :)

Go Sentry !

**Comment by marandaneto** [comment]
thanks @bsergean and keep us posted if you find anything :)

**Comment by bsergean** [comment]
Just tried 2.1.2 and I confirm that the fix works !! 

Thanks again @marandaneto

**Comment by cliffgr** [comment]
Hello all i am not sure tha issue is fixed. Because i have got that crash on 2.1.3 version too

**Comment by marandaneto** [comment]
Hello @cliffgr could you elaborate a bit more? OS version, maybe even the stack trace if you could reproduce it, thanks.

**Comment by cliffgr** [comment]
Sure

"brand": "samsung",
"model": "SM-N7505",
"osVersion": "5.1.1"

```java
java.lang.RuntimeException: Unable to get provider io.sentry.android.core.SentryInitProvider: java.lang.SecurityException: Neither user 10304 nor current process has android.permission.READ_PHONE_STATE.
        at android.app.ActivityThread.installProvider(ActivityThread.java:6456)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6048)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5988)
        at android.app.ActivityThread.access$1700(ActivityThread.java:211)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1766)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:145)
        at android.app.ActivityThread.main(ActivityThread.java:6912)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
     Caused by: java.lang.SecurityException: Neither user 10304 nor current process has android.permission.READ_PHONE_STATE.
        at android.os.Parcel.readException(Parcel.java:1546)
        at android.os.Parcel.readException(Parcel.java:1499)
        at com.android.internal.telephony.ITelephonyRegistry$Stub$Proxy.listenForSubscriber(ITelephonyRegistry.java:580)
        at android.telephony.TelephonyManager.listen(TelephonyManager.java:2832)
        at io.sentry.android.core.PhoneStateBreadcrumbsIntegration.register(PhoneStateBreadcrumbsIntegration.java:52)
        at io.sentry.core.Hub.<init>(Hub.java:38)
        at io.sentry.core.Sentry.init(Sentry.java:144)
        at io.sentry.core.Sentry.init(Sentry.java:92)
        at io.sentry.android.core.SentryAndroid.init(SentryAndroid.java:59)
        at io.sentry.android.core.SentryAndroid.init(SentryAndroid.java:32)
        at io.sentry.android.core.SentryInitProvider.onCreate(SentryInitProvider.java:25)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:1737)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:1712)
        at io.sentry.android.core.SentryInitProvider.attachInfo(SentryInitProvider.java:42)
        at android.app.ActivityThread.installProvider(ActivityThread.java:6453)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6048) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5988) 
        at android.app.ActivityThread.access$1700(ActivityThread.java:211) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1766) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:145) 
        at android.app.ActivityThread.main(ActivityThread.java:6912) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199) ```

**Comment by marandaneto** [comment]
@cliffgr the line numbers are odd, it looks like you are not using the SDK `2.1.3` version.
could you `gradlew clean cleanBuildCache` and also uninstall the Apk from the device, compile and install again?
guess you are using a cached version before the fix.

**Comment by cliffgr** [comment]
i am using Jenkijns ci to distibute an apk to our qa team

**Comment by bsergean** [comment]
We had our own QA verify a build with 2.1.2 on a lot of physical Android devices and the problem was gone, so I also suspect a bad build problem.

**Comment by cliffgr** [comment]
I will downgrade to 2.1.2 version and i will check again . 
Thanks in advance
