### ISSUE TITLE
Fail to send a crash event (Event submission failed)

### ISSUE THREAD

**Issue by batadamnjanovic** [getsentry/sentry-android#489]
_Platform:_
- [x] Android -> Android Emulator Nexus 5x 27(8.1.0), Compile SDK 29, Target SDK 29,  buildTools uses a default version of the build tools that the plugin specifies for Android Gradle plugin(4.0.0)

_IDE:_
- [x] Android Studio -> 4.0

_Build system:_
- [x]  Gradle -> 6.1.1

_Android Gradle Plugin:_
- [x] Yes -> 4.0.0

_Sentry Android Gradle Plugin:_
- [ ]  Yes -> If yes, which version?
- [x]  No

_Proguard/R8:_
- [ ]  Enabled
- [x]  Disabled

_sentry-android installed with:_
- [x] JCenter

The version of sentry-android:
**2.2.2**

---
I have the following issue:
Sentry does not send a crash event.

Error stacktrace:

```consumer.development I/Sentry: Uncaught exception received.
consumer.development D/Sentry: Capturing event: 0c52f0d75c734fbab55a2e629dc22702
consumer.development I/Sentry: Not possible to read external files directory
consumer.development I/Sentry: Session is null on scope.withSession
consumer.development D/Sentry: Adding Event to offline storage: /data/user/0/consumer.development/cache/sentry/0c52f0d75c734fbab55a2e629dc22702.sentry-event
consumer.development I/Sentry: Invoking inner uncaught exception handler.
consumer.development D/Sentry: Disk flush event fired: 0c52f0d75c734fbab55a2e629dc22702
consumer.development D/Sentry: Request failed, API returned 301
consumer.development E/Sentry: Event submission failed: 0c52f0d75c734fbab55a2e629dc22702
    java.lang.NullPointerException
        at java.io.Reader.<init>(Reader.java:78)
        at java.io.InputStreamReader.<init>(InputStreamReader.java:113)
        at io.sentry.core.transport.HttpTransport.getErrorMessageFromStream(HttpTransport.java:471)
        at io.sentry.core.transport.HttpTransport.readAndLog(HttpTransport.java:310)
        at io.sentry.core.transport.HttpTransport.send(HttpTransport.java:174)
        at io.sentry.core.transport.AsyncConnection$EventSender.flush(AsyncConnection.java:289)
        at io.sentry.core.transport.AsyncConnection$EventSender.run(AsyncConnection.java:258)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
consumer.development D/Sentry: io.sentry.core.UncaughtExceptionHandlerIntegration.UncaughtExceptionHint is not SubmissionResult
```

**Steps to reproduce:**
- Put `throw RuntimeException()` in Fragment's onViewCreated() method or anywhere

**Actual result:**
- Actual

**Expected result:**
- Result

**Comment by batadamnjanovic** [comment]
Also, when starting the app I have this log:

```
D/Sentry: SU doesn't exist.
    java.io.IOException: Cannot run program "/system/xbin/which": error=2, No such file or directory
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
        at java.lang.Runtime.exec(Runtime.java:692)
        at java.lang.Runtime.exec(Runtime.java:560)
        at io.sentry.android.core.util.RootChecker.checkSUExist(RootChecker.java:135)
        at io.sentry.android.core.util.RootChecker.isDeviceRooted(RootChecker.java:90)
        at io.sentry.android.core.DefaultAndroidEventProcessor.loadContextData(DefaultAndroidEventProcessor.java:122)
        at io.sentry.android.core.DefaultAndroidEventProcessor.lambda$new$0$DefaultAndroidEventProcessor(DefaultAndroidEventProcessor.java:110)
        at io.sentry.android.core.-$$Lambda$DefaultAndroidEventProcessor$ZsPdDrAaOs30gov_5eSNgy_KYe8.call(Unknown Source:2)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.io.IOException: error=2, No such file or directory
        at java.lang.UNIXProcess.forkAndExec(Native Method)
        at java.lang.UNIXProcess.<init>(UNIXProcess.java:133)
        at java.lang.ProcessImpl.start(ProcessImpl.java:128)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        at java.lang.Runtime.exec(Runtime.java:692) 
        at java.lang.Runtime.exec(Runtime.java:560) 
        at io.sentry.android.core.util.RootChecker.checkSUExist(RootChecker.java:135) 
        at io.sentry.android.core.util.RootChecker.isDeviceRooted(RootChecker.java:90) 
        at io.sentry.android.core.DefaultAndroidEventProcessor.loadContextData(DefaultAndroidEventProcessor.java:122) 
        at io.sentry.android.core.DefaultAndroidEventProcessor.lambda$new$0$DefaultAndroidEventProcessor(DefaultAndroidEventProcessor.java:110) 
        at io.sentry.android.core.-$$Lambda$DefaultAndroidEventProcessor$ZsPdDrAaOs30gov_5eSNgy_KYe8.call(Unknown Source:2) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
        at java.lang.Thread.run(Thread.java:764) 
```

**Comment by marandaneto** [comment]
> Also, when starting the app I have this log:
> 
> ```
> D/Sentry: SU doesn't exist.
>     java.io.IOException: Cannot run program "/system/xbin/which": error=2, No such file or directory
>         at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
>         at java.lang.Runtime.exec(Runtime.java:692)
>         at java.lang.Runtime.exec(Runtime.java:560)
>         at io.sentry.android.core.util.RootChecker.checkSUExist(RootChecker.java:135)
>         at io.sentry.android.core.util.RootChecker.isDeviceRooted(RootChecker.java:90)
>         at io.sentry.android.core.DefaultAndroidEventProcessor.loadContextData(DefaultAndroidEventProcessor.java:122)
>         at io.sentry.android.core.DefaultAndroidEventProcessor.lambda$new$0$DefaultAndroidEventProcessor(DefaultAndroidEventProcessor.java:110)
>         at io.sentry.android.core.-$$Lambda$DefaultAndroidEventProcessor$ZsPdDrAaOs30gov_5eSNgy_KYe8.call(Unknown Source:2)
>         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
>         at java.lang.Thread.run(Thread.java:764)
>      Caused by: java.io.IOException: error=2, No such file or directory
>         at java.lang.UNIXProcess.forkAndExec(Native Method)
>         at java.lang.UNIXProcess.<init>(UNIXProcess.java:133)
>         at java.lang.ProcessImpl.start(ProcessImpl.java:128)
>         at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
>         at java.lang.Runtime.exec(Runtime.java:692) 
>         at java.lang.Runtime.exec(Runtime.java:560) 
>         at io.sentry.android.core.util.RootChecker.checkSUExist(RootChecker.java:135) 
>         at io.sentry.android.core.util.RootChecker.isDeviceRooted(RootChecker.java:90) 
>         at io.sentry.android.core.DefaultAndroidEventProcessor.loadContextData(DefaultAndroidEventProcessor.java:122) 
>         at io.sentry.android.core.DefaultAndroidEventProcessor.lambda$new$0$DefaultAndroidEventProcessor(DefaultAndroidEventProcessor.java:110) 
>         at io.sentry.android.core.-$$Lambda$DefaultAndroidEventProcessor$ZsPdDrAaOs30gov_5eSNgy_KYe8.call(Unknown Source:2) 
>         at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
>         at java.lang.Thread.run(Thread.java:764) 
> ```

this is because you have `debug` enabled, it's not a bug.

**Comment by marandaneto** [comment]
hey @batadamnjanovic thanks for raising this.
do you use on-premise Sentry?

> Request failed, API returned 301

this looks like an issue in your Sentry and not in the SDK itself.

**Comment by vincent-paing** [comment]
I'm using self instance as well, and I checked every options, I set the right DNS, set the right auth token, everything's correct. However, it does not report on the dashboard at all. On `2.3.0`

**Comment by marandaneto** [comment]
thanks for letting us know
