### ISSUE TITLE
Application Not Responding for at least 5000 ms.

### ISSUE THREAD

**Issue by junaid-umar** [getsentry/sentry-android#526]
OS: Android 9.0
Dependency      'io.sentry:sentry-android:2.2.1'

io.sentry.android.core.ApplicationNotResponding: Application Not Responding for at least 5000 ms.
    at android.view.ViewGroup.dispatchVisibilityAggregated(ViewGroup.java:1562)
    at android.view.ViewGroup.dispatchVisibilityAggregated(ViewGroup.java:1567)
    at android.view.ViewGroup.attachViewToParent(ViewGroup.java:5696)
    at android.support.v7.widget.RecyclerView.access$000(RecyclerView.java:207)
    at android.support.v7.widget.RecyclerView$5.attachViewToParent(RecyclerView.java:922)
    at android.support.v7.widget.ChildHelper.attachViewToParent(ChildHelper.java:239)
    at android.support.v7.widget.RecyclerView$LayoutManager.addViewInt(RecyclerView.java:8317)
    at android.support.v7.widget.RecyclerView$LayoutManager.addView(RecyclerView.java:8294)
    at android.support.v7.widget.RecyclerView$LayoutManager.addView(RecyclerView.java:8282)
    at android.support.v7.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:580)
    at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1517)
    at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:612)
    at android.support.v7.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:171)
    at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3924)
    at android.support.v7.widget.RecyclerView.onMeasure(RecyclerView.java:3336)
    at android.view.View.measure(View.java:23187)
    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6752)
    at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1535)
    at android.widget.LinearLayout.measureVertical(LinearLayout.java:825)
    at android.widget.LinearLayout.onMeasure(LinearLayout.java:704)
    at android.view.View.measure(View.java:23187)
    at android.support.v4.widget.NestedScrollView.measureChildWithMargins(NestedScrollView.java:1502)
    at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
    at android.support.v4.widget.NestedScrollView.onMeasure(NestedScrollView.java:556)
    at android.view.View.measure(View.java:23187)
    at android.widget.RelativeLayout.measureChild(RelativeLayout.java:676)
    at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:479)
    at android.view.View.measure(View.java:23187)
    at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1638)
    at android.view.View.measure(View.java:23187)
    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6752)
    at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1535)
    at android.widget.LinearLayout.measureVertical(LinearLayout.java:825)
    at android.widget.LinearLayout.onMeasure(LinearLayout.java:704)
    at android.view.View.measure(View.java:23187)
    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6752)
    at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
    at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:143)
    at android.view.View.measure(View.java:23187)
    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6752)
    at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1535)
    at android.widget.LinearLayout.measureVertical(LinearLayout.java:825)
    at android.widget.LinearLayout.onMeasure(LinearLayout.java:704)
    at android.view.View.measure(View.java:23187)
    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6752)
    at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
    at android.view.View.measure(View.java:23187)
    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6752)
    at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1535)
    at android.widget.LinearLayout.measureVertical(LinearLayout.java:825)
    at android.widget.LinearLayout.onMeasure(LinearLayout.java:704)
    at android.view.View.measure(View.java:23187)
    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6752)
    at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
    at com.android.internal.policy.DecorView.onMeasure(DecorView.java:755)
    at android.view.View.measure(View.java:23187)
    at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2757)
    at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1606)
    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1890)
    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1494)
    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7288)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
    at android.view.Choreographer.doCallbacks(Choreographer.java:761)
    at android.view.Choreographer.doFrame(Choreographer.java:696)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
    at android.os.Handler.handleCallback(Handler.java:873)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:193)
    at android.app.ActivityThread.main(ActivityThread.java:6923)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:870)

**Comment by marandaneto** [comment]
@junaid-umar please use the issue template -> https://github.com/getsentry/sentry-android/issues/new/choose

I don't follow that's the problem, please explain.
