### ISSUE TITLE
Android 11 + targetSdkVersion 30 crashes Sentry on start

### ISSUE THREAD

**Issue by SalvatoreT** [getsentry/sentry-android#550]
_Platform:_
- [x]  Android, targetSdkVersion 30
- [x]  Java
- [ ]  Kotlin
- [ ]  NDK
- [ ]  React-Native

_IDE:_
- [x]  Android Studio
- [ ]  IntelliJ
- [ ]  Other

The version of sentry-android:
**2.3.0**(at least) - **master**

---
I have the following issue:

When I set the targetSdkVersion to 30 for my app and launch it on an Android 11 device (my Pixel 4XL), the app crashes immediately.

**Steps to reproduce:**
1. Clone the `sentry-android` repository
2. Change the example app to use `targetSdkVersion` 30.
```diff
diff --git a/sentry-samples/sentry-samples-android/build.gradle.kts b/sentry-samples/sentry-samples-android/build.gradle.kts
index 5c29345..d299d1b 100644
--- a/sentry-samples/sentry-samples-android/build.gradle.kts
+++ b/sentry-samples/sentry-samples-android/build.gradle.kts
@@ -10,7 +10,7 @@ android {
     defaultConfig {
         applicationId = "io.sentry.samples.android"
         minSdkVersion(Config.Android.minSdkVersionNdk)
-        targetSdkVersion(Config.Android.targetSdkVersion)
+        targetSdkVersion(30)
         versionCode = 2
         versionName = "1.1.0"
```
3. launch `sentry-samples-android`

**Actual result:**
- Immediate crash
```
            libc  F  Pointer tag for 0x79f0abdc30 was truncated.
          Sentry  D  Processing dir. /data/user/0/io.sentry.samples.android/cache/sentry/sessions
            libc  F  Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 15999 (samples.android), pid 15999 (samples.android)
          Sentry  D  Processing 6 items from cache dir /data/user/0/io.sentry.samples.android/cache/sentry/sessions
                  D  Processing file: /data/user/0/io.sentry.samples.android/cache/sentry/sessions/f146b6e6-91af-4a2f-a08c-014613f5e594.envelope
                  D  Processing Envelope with 1 item(s)
                  D  Captured Envelope is already cached
                  D  Item 1 is being captured.
                  D  Going to wait flush 1 item.
TetheringManager  I  registerTetheringEventCallback:io.sentry.samples.android
           DEBUG  F  #00 pc 000000000004de4c  /apex/com.android.runtime/lib64/bionic/libc.so (abort+164) (BuildId: 03452a4a418e14ff93948f26561eace6)
                  F  #01 pc 000000000003bb34  /apex/com.android.runtime/lib64/bionic/libc.so (free+96) (BuildId: 03452a4a418e14ff93948f26561eace6)
                  F  #02 pc 00000000000781a8  /data/app/~~gQctd6Q5azmrHpqfGRaWvQ==/io.sentry.samples.android-IaNp2cunocnQXp3s03mjng==/lib/arm64/libsentry.so (sentry_f
                     ree+36) (BuildId: a8252e0bb65f23db1c6420f10a30b2f3b1477309)
                  F  #03 pc 0000000000085880  /data/app/~~gQctd6Q5azmrHpqfGRaWvQ==/io.sentry.samples.android-IaNp2cunocnQXp3s03mjng==/lib/arm64/libsentry.so (BuildId:
                      a8252e0bb65f23db1c6420f10a30b2f3b1477309)
                  F  #04 pc 0000000000085710  /data/app/~~gQctd6Q5azmrHpqfGRaWvQ==/io.sentry.samples.android-IaNp2cunocnQXp3s03mjng==/lib/arm64/libsentry.so (sentry_v
                     alue_decref+92) (BuildId: a8252e0bb65f23db1c6420f10a30b2f3b1477309)
                  F  #05 pc 000000000007f038  /data/app/~~gQctd6Q5azmrHpqfGRaWvQ==/io.sentry.samples.android-IaNp2cunocnQXp3s03mjng==/lib/arm64/libsentry.so (BuildId:
                      a8252e0bb65f23db1c6420f10a30b2f3b1477309)
```

**Expected result:**
- No crash

**Comment by marandaneto** [comment]
hey @SalvatoreT thanks for raising this.

could you try to debug it and see what happens and where?
I can't reproduce it using a Pixel 3 XL, it works just fine.

**Comment by SalvatoreT** [comment]
@marandaneto, are you running Android 11?

**Comment by marandaneto** [comment]
@SalvatoreT an emulator, but yes

<img width="921" alt="Screenshot 2020-09-10 at 09 41 29" src="https://user-images.githubusercontent.com/5731772/92696185-cf0b2e00-f349-11ea-9cee-4a496e6e07b4.png">

**Comment by marandaneto** [comment]
I have a Pixel 2 XL device and its upgrading to Android 11, I will test it again once its finished.

**Comment by marandaneto** [comment]
<img width="903" alt="Screenshot 2020-09-10 at 09 59 14" src="https://user-images.githubusercontent.com/5731772/92698121-4a6ddf00-f34c-11ea-8bb8-cc3072e452c8.png">

it worked just fine as well.

**Comment by LearnerMN** [comment]
Same here. I have tested this thing on the Pixel 4a with OS 11 and it doesn't work but it works on the Pixel 3a with OS 11. Something wrong on the Pixel 4* with OS 11...

**Comment by AdamMc331** [comment]
Having a similar issue on Pixel 4 as well. Seeing this error log whenever I run my app:

```
2020-09-10 14:58:36.005 30419-30419 D/Sentry: Auto-init: false
2020-09-10 14:58:36.005 30419-30419 I/Sentry: Retrieving auto-init from AndroidManifest.xml
2020-09-10 14:58:36.169 30419-30520 I/Sentry: sentry-debug-meta.properties file was not found.
2020-09-10 14:58:36.188 30419-30520 D/Sentry: SU doesn't exist.
    java.io.IOException: Cannot run program "/system/xbin/which": error=2, No such file or directory
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1050)
        at java.lang.Runtime.exec(Runtime.java:699)
        at java.lang.Runtime.exec(Runtime.java:564)
        at io.sentry.android.core.util.RootChecker.checkSUExist(RootChecker.java:135)
        at io.sentry.android.core.util.RootChecker.isDeviceRooted(RootChecker.java:90)
        at io.sentry.android.core.DefaultAndroidEventProcessor.loadContextData(DefaultAndroidEventProcessor.java:114)
        at io.sentry.android.core.DefaultAndroidEventProcessor.lambda$new$0$DefaultAndroidEventProcessor(DefaultAndroidEventProcessor.java:102)
        at io.sentry.android.core.-$$Lambda$DefaultAndroidEventProcessor$ZsPdDrAaOs30gov_5eSNgy_KYe8.call(Unknown Source:2)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
     Caused by: java.io.IOException: error=2, No such file or directory
        at java.lang.UNIXProcess.forkAndExec(Native Method)
        at java.lang.UNIXProcess.<init>(UNIXProcess.java:133)
        at java.lang.ProcessImpl.start(ProcessImpl.java:141)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        at java.lang.Runtime.exec(Runtime.java:699) 
        at java.lang.Runtime.exec(Runtime.java:564) 
        at io.sentry.android.core.util.RootChecker.checkSUExist(RootChecker.java:135) 
        at io.sentry.android.core.util.RootChecker.isDeviceRooted(RootChecker.java:90) 
        at io.sentry.android.core.DefaultAndroidEventProcessor.loadContextData(DefaultAndroidEventProcessor.java:114) 
        at io.sentry.android.core.DefaultAndroidEventProcessor.lambda$new$0$DefaultAndroidEventProcessor(DefaultAndroidEventProcessor.java:102) 
        at io.sentry.android.core.-$$Lambda$DefaultAndroidEventProcessor$ZsPdDrAaOs30gov_5eSNgy_KYe8.call(Unknown Source:2) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:923) 
```

Originally I suspected an error with Android's new [Wireless ADB](https://developer.android.com/about/versions/11/features#wireless-adb) feature that I was trying, but even plugging the phone in manually didn't work. 

I'm able to run on a Pixel 3a emulator with Android 11 just fine.

**Comment by jamesarich** [comment]
Also experiencing this crash when running on a Pixel 4a device w/ Android 11.
